title: Papiya Sarees
author: Papiya Dubey
email: papiya.dubey123@gmail.com
description: >-
  This is a catalogue website where you can view different range of 
  dress and sarees.

social:
  twitter: 
  facebook: 
  instagram: 
  github: 
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
